name: Bug report
description: Report a problem that affects verification or behavior
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include steps to reproduce
      placeholder: Description...
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence (logs, eval rows, screenshots)
      description: Link to `/evals/runs/*` or screenshots
  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: e.g., v0.2 / abc123
